directory:  /home/casa/tmp
email:
  smtp_host: smtp.orange.fr
  recipient: casa@sweetohm.net
  sender:    casa@sweetohm.net
  success:   true

modules:
  continuum:
    url:     https://github.com/c4s4/continuum.git
    command: |
      set -e
      export PATH=/opt/python/current/bin:$PATH
      virtualenv env --no-site-packages
      . env/bin/activate
      pip install -r etc/requirements.txt
      bee test

